export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export const FETCH_ISSUES_REQUESTED = 'FETCH_ISSUES_REQUESTED';
export const FETCH_ISSUES_LOADED = 'FETCH_ISSUES_LOADED';
export const FETCH_ISSUES_FAILED = 'FETCH_ISSUES_FAILED';

export const FETCH_REPOSITORIES_REQUESTED = 'FETCH_REPOSITORIES_REQUESTED';

export const FETCH_REPOSITORY_REQUESTED = 'FETCH_REPOSITORY_REQUESTED';
export const FETCH_REPOSITORY_LOADED = 'FETCH_REPOSITORY_LOADED';
export const FETCH_REPOSITORY_FAILED = 'FETCH_REPOSITORY_FAILED';

export const ADD_REPOSITORY = 'ADD_REPOSITORY';
export const REMOVE_REPOSITORY = 'REMOVE_REPOSITORY';

export const CORNIFY = 'CORNIFY';
